# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0002_auto_20160818_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('matricula_key', models.CharField(db_index=True, max_length=40, verbose_name='Chave da matricula')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='cat.Pessoa')),
            ],
            options={
                'ordering': ['treinamento', 'pessoa'],
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('qtd_dia', models.IntegerField(verbose_name='Quantidade de dias')),
                ('dia_util', models.BooleanField(default=False, help_text='Contabilizar apenas os dias úteis', verbose_name='Dia útil')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('rotina', 'Rotina')], max_length=25)),
                ('prazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr.Prazo')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='ctr.Treinamento'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('matricula_key', 'treinamento', 'pessoa')]),
        ),
    ]
