# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia',
            options={'verbose_name': 'Agência', 'verbose_name_plural': 'Agências'},
        ),
        migrations.AlterModelOptions(
            name='regional',
            options={'verbose_name_plural': 'Regionais'},
        ),
    ]
