# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cag', '0002_auto_20160818_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regional',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Regionais'},
        ),
    ]
