# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cag', '0003_auto_20160818_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia',
            options={'ordering': ['nome'], 'verbose_name': 'Agência', 'verbose_name_plural': 'Agências'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['sigla']},
        ),
    ]
