# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nome']},
        ),
    ]
