# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20160818_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='cat.Pessoa'),
        ),
    ]
