# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20160820_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='matricula',
            field=models.CharField(help_text='A matricula deve ser única.', max_length=15),
        ),
    ]
